version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: OrderAppDb
    environment:
      SA_PASSWORD: "MyStr!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - orderapp-network

volumes:
  sqlserver-data:

networks:
  orderapp-network:
